/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author estudiante
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        desktopPane.setSize(screenSize.width, screenSize.height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        desktopPane = new javax.swing.JDesktopPane();
        Contenedor = new javax.swing.JInternalFrame();
        txtUsuario = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnUsuarios = new javax.swing.JButton();
        btnProgramas = new javax.swing.JButton();
        btnDocentes = new javax.swing.JButton();
        btnAsignatura = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ItemSalir = new javax.swing.JMenuItem();
        mParametrizacion = new javax.swing.JMenu();
        ItemProgramas = new javax.swing.JMenuItem();
        ItemAsignaturas = new javax.swing.JMenuItem();
        ItemTiposDocumentos = new javax.swing.JMenuItem();
        ItemSalones = new javax.swing.JMenuItem();
        ItemDias = new javax.swing.JMenuItem();
        ItemProfesiones = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mItemRoles = new javax.swing.JMenuItem();
        ItemUsuarios = new javax.swing.JMenuItem();
        ItemMiPerfil = new javax.swing.JMenuItem();
        itemAdministracion = new javax.swing.JMenu();
        itemDocentes = new javax.swing.JMenuItem();
        ItemDisponibilidad = new javax.swing.JMenuItem();
        ItemHorarios = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu4.setText("Edit");
        jMenuBar1.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(65, 105, 170));

        desktopPane.setLayout(null);

        Contenedor.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        Contenedor.setVisible(false);

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor.getContentPane());
        Contenedor.getContentPane().setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(Contenedor);
        Contenedor.setBounds(180, 30, 310, 200);

        txtUsuario.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setText("jLabel1");
        desktopPane.add(txtUsuario);
        txtUsuario.setBounds(10, 10, 420, 30);

        jPanel1.setBackground(new java.awt.Color(65, 105, 170));
        jPanel1.setForeground(new java.awt.Color(65, 105, 170));

        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user.png"))); // NOI18N
        btnUsuarios.setText("Usuarios");

        btnProgramas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/education.png"))); // NOI18N
        btnProgramas.setText("Programas");

        btnDocentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/people.png"))); // NOI18N
        btnDocentes.setText("Docentes");

        btnAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/file.png"))); // NOI18N
        btnAsignatura.setText("Asignaturas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnProgramas, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProgramas, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(btnAsignatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDocentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenu1.setText("Archivo");

        ItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        ItemSalir.setText("Salir");
        jMenu1.add(ItemSalir);

        menuBar.add(jMenu1);

        mParametrizacion.setText("Parametrización");

        ItemProgramas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        ItemProgramas.setText("Programas");
        mParametrizacion.add(ItemProgramas);

        ItemAsignaturas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        ItemAsignaturas.setText("Asignaturas");
        mParametrizacion.add(ItemAsignaturas);

        ItemTiposDocumentos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        ItemTiposDocumentos.setText("Tipos de Documentos");
        mParametrizacion.add(ItemTiposDocumentos);

        ItemSalones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        ItemSalones.setText("Salones");
        mParametrizacion.add(ItemSalones);

        ItemDias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        ItemDias.setText("Dias");
        mParametrizacion.add(ItemDias);

        ItemProfesiones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        ItemProfesiones.setText("Profesiones");
        mParametrizacion.add(ItemProfesiones);

        menuBar.add(mParametrizacion);

        jMenu3.setText("Seguridad");

        mItemRoles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        mItemRoles.setText("Roles");
        mItemRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemRolesActionPerformed(evt);
            }
        });
        jMenu3.add(mItemRoles);

        ItemUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        ItemUsuarios.setText("Usuarios");
        ItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemUsuariosActionPerformed(evt);
            }
        });
        jMenu3.add(ItemUsuarios);

        ItemMiPerfil.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        ItemMiPerfil.setText("Mi Perfil");
        ItemMiPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemMiPerfilActionPerformed(evt);
            }
        });
        jMenu3.add(ItemMiPerfil);

        menuBar.add(jMenu3);

        itemAdministracion.setText("Administración");

        itemDocentes.setText("Docentes");
        itemAdministracion.add(itemDocentes);

        ItemDisponibilidad.setText("Disponibilidades");
        itemAdministracion.add(ItemDisponibilidad);

        ItemHorarios.setText("Horarios");
        itemAdministracion.add(ItemHorarios);

        menuBar.add(itemAdministracion);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemMiPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemMiPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemMiPerfilActionPerformed

    private void mItemRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemRolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mItemRolesActionPerformed

    private void ItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JInternalFrame Contenedor;
    public javax.swing.JMenuItem ItemAsignaturas;
    public javax.swing.JMenuItem ItemDias;
    public javax.swing.JMenuItem ItemDisponibilidad;
    public javax.swing.JMenuItem ItemHorarios;
    public javax.swing.JMenuItem ItemMiPerfil;
    public javax.swing.JMenuItem ItemProfesiones;
    public javax.swing.JMenuItem ItemProgramas;
    public javax.swing.JMenuItem ItemSalir;
    public javax.swing.JMenuItem ItemSalones;
    public javax.swing.JMenuItem ItemTiposDocumentos;
    public javax.swing.JMenuItem ItemUsuarios;
    public javax.swing.JButton btnAsignatura;
    public javax.swing.JButton btnDocentes;
    public javax.swing.JButton btnProgramas;
    public javax.swing.JButton btnUsuarios;
    public javax.swing.JDesktopPane desktopPane;
    public javax.swing.JMenu itemAdministracion;
    public javax.swing.JMenuItem itemDocentes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JMenuItem mItemRoles;
    public javax.swing.JMenu mParametrizacion;
    private javax.swing.JMenuBar menuBar;
    public javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables

}
